name: dr_fix
description: A smart AI-powered maintenance assistant application for Jordan & GCC.
publish_to: 'none'
version: 1.1.4+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3
  image_picker: ^1.1.2
  google_maps_flutter: ^2.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0 # تم إضافة حزمة قراءة إحداثيات الـ GPS لتحديد عملة الفني حركياً
  pdf: ^3.13.0
  path_provider: ^2.1.6
  shared_preferences: ^2.2.3 # تم تأمين حزمة حفظ الهوية والاسم الفني للمستخدم تلقائياً
  crypto: ^3.0.7 # لتشفير كلمة مرور الأدمن كـ SHA-256
  flutter_dotenv: ^5.1.0 # إضافة الحزمة
  url_launcher: ^6.2.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.4.4
  http: ^1.6.0
  google_generative_ai: ^0.4.7
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_config.env
  # تم تطهير وحذف سطر الأصول الخارجي assets/logo.png التزاماً بشرط الهوية البرمجية الصافية 100%

flutter_launcher_icons:
  ios: true
  android: false
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true